### ISSUE TITLE
Металичность в шейдерах не влияет на визуал

### ISSUE THREAD

**Issue by MihaPro-CarX** [yelelexA/TheCoolestGarage#1]
При изменении в редакторе настройки Metalic незамечено изменение вида объекта.

**Comment by yelelexA** [comment]
> При изменении в редакторе настройки Metalic незамечено изменение вида объекта.

Исправил опечатку с "Metalic" на "Metallic" во всех шейдерах, где предусмотрена данная настройка - все работает.

[Все исправления описаны в коммите "FixBugs"]
