### ISSUE TITLE
Материал машины в мировых координатах

### ISSUE THREAD

**Issue by MihaPro-CarX** [yelelexA/TheCoolestGarage#2]
При перемещении машины текстура на ней начинает "ездить", а должна оставать на машине статично.

**Comment by yelelexA** [comment]
> При перемещении машины текстура на ней начинает "ездить", а должна оставать на машине статично.

Перенёс вычисления из мировых координат в координаты объекта. Теперь, при перемещении объекта на сцене, текстура остается статичной.

[Все исправления описаны в коммите "FixBugs"]
