### ISSUE TITLE
Непрозрачность стекла

### ISSUE THREAD

**Issue by MihaPro-CarX** [yelelexA/TheCoolestGarage#3]
Шейдер стекла при максимальной непрозрачности всё равно визуально оставляет прозрачное стекло. Можно ли сделать так, чтоб в случае Opacity 1 стекло было абсолютно чёрным?

**Comment by yelelexA** [comment]
Исправил смешивание альфа-канала с текстурой. Также добавил возможность регулировать силу непрозрачности (в инспекторе "OpacityPower"). Теперь стало возможным сделать стекло абсолютно черным.

[Все исправления описаны в коммите "FixBugs"]

**Comment by yelelexA** [comment]
> Шейдер стекла при максимальной непрозрачности всё равно визуально оставляет прозрачное стекло. Можно ли сделать так, чтоб в случае Opacity 1 стекло было абсолютно чёрным?

Исправил смешивание альфа-канала с текстурой. Также добавил возможность регулировать силу непрозрачности (в инспекторе "OpacityPower"). Теперь стало возможным сделать стекло абсолютно черным.

[Все исправления описаны в коммите "FixBugs"]

**Comment by MihaPro-CarX** [comment]
После правок по прозрачности возникли следующие вопросы:

1. Почему пояилось новое значение OpacityPower, причём со странным диапазоном [1..2]?
2. С чем связано такое поведение, что в максимально непрозрачных настройках у машины всё равно прозрачное стекло, а в гараже окно стало чёрным?
![изображение](https://user-images.githubusercontent.com/26853846/160113440-796d5f3f-4dc7-4ec1-a3a6-ae81a310262c.png)
3. Можно ли изменить шейдер так, чтоб за прозрачность отвечал один параметр Opacity [0..1] и чтоб тонирование стекла производилось дополнительным параметром Color?

**Comment by yelelexA** [comment]
> После правок по прозрачности возникли следующие вопросы:
> 
> 1. Почему пояилось новое значение OpacityPower, причём со странным диапазоном [1..2]?
> 2. С чем связано такое поведение, что в максимально непрозрачных настройках у машины всё равно прозрачное стекло, а в гараже окно стало чёрным?
>    ![изображение](https://user-images.githubusercontent.com/26853846/160113440-796d5f3f-4dc7-4ec1-a3a6-ae81a310262c.png)
> 3. Можно ли изменить шейдер так, чтоб за прозрачность отвечал один параметр Opacity [0..1] и чтоб тонирование стекла производилось дополнительным параметром Color?

1) Добавил для возможности регулировки силы непрозрачности. Данный диапазон был выбран, потому что значения <1 приводили к уменьшению непрозрачности, а значения >2 были равносильны значению =2.
2) Вероятнее всего из-за источника света над машиной.
3) Переписал шейдер. Теперь за прозрачность отвечает лишь один параметр Opacity [0..1], а также появилась возможность тонировать стекло с помощью  параметра Color. (Прим. Я специально сделал так, что тонировка стекла происходит только в черных или серых тонах. В случае необходимости, могу добавить возможность создания цветной тонировки стекла)

[Все исправления описаны в коммите "UpdateGlass"]

**Comment by MihaPro-CarX** [comment]
В материале неправильная ссылка на шейдер.
При восстановлении ссылки нет ожидаемого поведения.
Полная непрозрачность должна давать чистый цвет тонировки.
![Uploading изображение.png…]()

**Comment by yelelexA** [comment]
Я правильно понимаю, вы ожидаете, что при полной непрозрачности, стекло  не должно иметь вообще никаких просветов, как на примере ниже? (В данном случае шейдер стекла используется на кубах)

![image](https://user-images.githubusercontent.com/78636517/160355395-766724f1-8392-49ee-bcd4-be0d303754bf.png)

**Comment by MihaPro-CarX** [comment]
Естественно. Полная непрозрачность о том и говорит, что ничего не пропускает. Соотвественно, цвет будет точно такой же как указан в Color.

**Comment by yelelexA** [comment]
> Естественно. Полная непрозрачность о том и говорит, что ничего не пропускает. Соотвественно, цвет будет точно такой же как указан в Color.

Исправил!

**Comment by MihaPro-CarX** [comment]
Всё заработало, поздравляю!
